### ISSUE TITLE
The third column of the sticker picker is invisible

### ISSUE THREAD

**Issue by ritokatsuga** [DiscordStyles/Fluent#89]
### Describe the bug

Every time I open up the sticker picker, the third column is just invisible and unreachable due to range between stickers are now larger than before.

### To Reproduce

Open the sticker picker pop up window

### Screenshots

When the theme applied
![image](https://user-images.githubusercontent.com/35857106/204007458-05272143-9cee-486a-b9a2-79e25bd845f1.png)
 
When without theme
![image](https://user-images.githubusercontent.com/35857106/204007522-4113e1bc-6355-41e0-aaae-ed949832a4b9.png)

### Infomation (please complete the following information)

**Discord channel**: Stable
**OS**: Windows  
**Mod**: BetterDiscord
**Discord language**: English (UK)

**Comment by Gibbu** [comment]
Discord and their infinite wisdom have decided to place a very specific value for the spacing between each sticker.
Instead of using a existing rule that'll do it for them automatically.

So, the 3rd sticker is actually behind the first sticker of the next row.

I'll fix it sooner or later but for now you can increase the width of the picker by dragging the left side.
![Discord_e0uJeVVBNv](https://user-images.githubusercontent.com/20338746/205242830-0e92667d-fdb5-4096-8535-880f8b0d1a26.png)

**Comment by ritokatsuga** [comment]
I can't believe what I just saw, really. Discord had been made the sticker picker that way for years so I don't have idea they are resizable now. Thank you, I'll resize mine on my end for now. Great job with the theme.
